# Generated by Django 3.1 on 2020-08-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(default='is item')),
                ('price', models.TextField(default='x')),
                ('active', models.TextField(default='yum')),
            ],
        ),
    ]
