# Generated by Django 3.1 on 2020-08-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200818_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myip',
        ),
    ]
