# Generated by Django 3.1 on 2020-08-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=256)),
                ('user', models.TextField(blank=True, null=True)),
                ('ip', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
